### Get All Contacts
GET http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

###

### Get a Single Contact
GET http://localhost:3000/api/items/60d0fe4f5311236168a109ca HTTP/1.1
Content-Type: application/json

###

### Create a New Contact
POST http://localhost:3000/api/items HTTP/1.1
Content-Type: application/json

{
    "name": "Test Item",
    "description": "This is a test item",
    "category": "Test Category",
    "price": 9.99,
    "stock": 100,
    "rating": 5
}

###

### Update a Contact
PUT http://localhost:3000/api/items/66776e053f69c037b47cf03f HTTP/1.1
Content-Type: application/json

{
    "name": "Updated Item",
    "description": "This is an updated test item",
    "category": "Updated Category",
    "price": 19.99,
    "stock": 50,
    "rating": 4
}

###

### Delete a Contact
DELETE http://localhost:3000/api/items/60d0fe4f5311236168a109ca HTTP/1.1
Content-Type: application/json

###

### Get All Users
GET http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

###

### Get a Single User
GET http://localhost:3000/api/users/60d0fe4f5311236168a109cb HTTP/1.1
Content-Type: application/json

###

### Create a New User
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "googleId": "testgoogleid",
    "displayName": "Test User",
    "email": "testuser@example.com"
}

###

### Update a User
PUT http://localhost:3000/api/users/66776fd13f69c037b47cf04f HTTP/1.1
Content-Type: application/json

{
    "displayName": "Updated User",
    "email": "updateduser@example.com"
}

###

### Delete a User
DELETE http://localhost:3000/api/users/60d0fe4f5311236168a109cb HTTP/1.1
Content-Type: application/json

###